// src/data/translations.js

const translations = {
  "सिरदर्द": "headache",
  "ताप": "fever",
  "सर्दी": "cold",
  "खोकला": "cough",
  "दुखणे": "pain",
  "पोटदुखी": "stomach ache",
  "थकवा": "fatigue",
  "श्वासोच्छवासाचा त्रास": "breathing problem",
  "उलटी": "vomiting",
  "चक्कर येणे": "dizziness",
  "त्वचेचा पुरळ": "skin rash",
  "डोळे दुखणे": "eye pain",
  "नाक वाहणे": "runny nose",
  "अतिसार": "diarrhea",
  "कोरडा खोकला": "dry cough",
  "ओला खोकला": "wet cough",
  "घशात खवखव": "sore throat",
  "शरीरावर सूज": "swelling",
  "सांधेदुखी": "joint pain",
  "पाठीचा त्रास": "back pain",
  "तोंडात दुखापत": "mouth ulcer",
  "तोंड येणे": "mouth infection",
  "डोके दुखणे": "migraine",
  "कान दुखणे": "ear pain",
  "कानात संसर्ग": "ear infection",
  "डोळ्यांची जळजळ": "eye irritation",
  "घसा दुखणे": "throat infection",
  "पोटात गडगड": "stomach upset",
  "अपचन": "indigestion",
  "अ‍ॅसिडिटी": "acidity",
  "गॅस्ट्रिक समस्या": "gastric problem",
  "उदरशूल": "abdominal cramps",
  "मळमळ": "nausea",
  "कमी रक्तदाब": "low blood pressure",
  "जास्त रक्तदाब": "high blood pressure",
  "मधुमेह": "diabetes",
  "अॅनिमिया": "anemia",
  "आर्थरायटिस": "arthritis",
  "संधिवात": "rheumatoid arthritis",
  "त्वचारोग": "skin disease",
  "फुफ्फुसाचा संसर्ग": "lung infection",
  "डेंग्यू": "dengue",
  "मलेरिया": "malaria",
  "टायफॉईड": "typhoid",
  "हिवताप": "malaria",
  "हातापायाला कंप": "tremors",
  "नसा दुखणे": "nerve pain",
  "मानदुखी": "neck pain",
  "हात दुखणे": "hand pain",
  "पाय दुखणे": "leg pain",
  "पाठ दुखणे": "backache",
  "छातीत दुखणे": "chest pain",
  "हृदय विकार": "heart disease",
  "श्वास घेण्यास त्रास": "breathlessness",
  "थंडी": "cold",
  "कावीळ": "jaundice",
  "सोरायसिस": "psoriasis",
  "पिंपल्स": "pimples",
  "फोड येणे": "boils",
  "अॅलर्जी": "allergy",
  "डोळा येणे": "eye infection",
  "तोंडात व्रण": "mouth ulcer",
  "गुदद्वारावर वेदना": "anal pain",
  "गुदद्वारावर सूज": "anal swelling",
  "मूत्र tract संसर्ग": "urine infection",
  "मूत्र मार्गाचे इन्फेक्शन": "urine infection",
  "लघवीत जळजळ": "burning urination",
  "पायाला सूज": "leg swelling",
  "हाताला सूज": "hand swelling",
  "अंगातील कंप": "body shivering",
  "लाल चट्टे": "red patches",
  "त्वचा खाज": "skin itching",
  "डोळ्यात दुखापत": "eye injury",
  "मणक्याचा त्रास": "spinal problem",
  "हात सुन्न होणे": "numbness in hand",
  "पाय सुन्न होणे": "numbness in leg",
  "हाडांची कमकुवतता": "weak bones",
  "हातापायाला मुंग्या येणे": "tingling sensation",
  "अन्ननलिकेचा त्रास": "esophagus problem",
  "अन्नपचनाच्या समस्या": "digestive problem",
  "अचानक चक्कर येणे": "sudden dizziness",
  "आतड्याचा त्रास": "intestinal problem",
  "पचनसंस्थेचा त्रास": "digestive system problem",
  "श्वसन संस्थेचा त्रास": "respiratory problem",
  "फुप्फुसाचा कर्करोग": "lung cancer",
  "त्वचेचा कर्करोग": "skin cancer",
  "हाडांचा कर्करोग": "bone cancer",
  "डोळ्याचा कर्करोग": "eye cancer",
  "घश्याचा कर्करोग": "throat cancer",
  "यकृताचा कर्करोग": "liver cancer",
  "पचनसंस्थेचा कर्करोग": "digestive cancer",
  "स्नायूंचा त्रास": "muscle pain",
  "तणाव": "stress",
  "अती चिंता": "anxiety",
  "उदासी": "depression",
};

export function translateToEnglish(input) {
  input = input.trim();
  return translations[input] || input;
}
